# config.yaml

# MCMC run configuration.
mcmc:
  num_iterations: 100000          # Total number of MCMC iterations.
  num_iterations_debug: 10000    # Number of iterations to print debug information.
  K: 3                         # Latent dimension (number of columnsin U).
  update_probabilities:
    rho: 0.2                   # Proportion of iterations to update rho.
    noise: 0.2                 # Proportion of iterations to update noise parameters.
    tau: 0.2                   # Proportion of iterations to update tau.
    U_0: 0.1                     # Proportion of iterations to update the latent variable U
    U_a: 0.3                    # There are more matrix parameters in the Ua thus we assigner higher prob

    K: 0.2                     # Proportion of iterations to update the number of latent dimensions K.
reversible_two_factors:
  rho_tau_update: False 


# Configuration for updating ρ.
rho:
  dr: 0.8                     # Multiplicative step size for rho update.

# Configuration for updating ρ&τ.
rhotau:
  drrt: 0.5            # Multiplicative step size for rho tau update.


# Configuration for noise parameter updates.
noise:
  noise_option: "queue_jump"  # Options: "mallows_noise" or "queue_jump".
  sigma_mallow: 0.5           # Proposal standard deviation for Mallows theta update.

# Prior parameters.
prior:
  rho_prior: 0.16667          # Prior parameter for rho.
  noise_beta_prior: 9       # Beta prior parameter for the noise parameter.
  mallow_ua: 10             # Exponential rate parameter for Mallows theta.

